config/routes.rb
Ruckus::Application.routes.draw do

  namespace :admin do resources :pages end

  resources :pages

  devise_for :users
  
  match '/:title/' => 'pages#show'
  

  root :to => "pages#home"

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :setpages
  layout :layout_by_resource
  
  def setpages
    @pages = Page.all
  end
  
  def layout_by_resource
    if devise_controller?
      "admin"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.xml
  before_filter :authenticate_user!, :except => ["home", "show"]
  
  def index
      respond_to do |format|
        format.html {render :layout => 'admin'}
        format.xml  { render :xml => @pages }
      end
  end
  
  
  def home
    if User.all.length < 1
      redirect_to new_registration_path('user')
    else
      @page = Page.first
      respond_to do |format|
        format.html { render :action => 'show'}
        format.xml  { render :xml => @pages }
      end
    end
  end

  # GET /pages/1
  # GET /pages/1.xml
  def show
    puts "Looking for page by title: #{params[:id]}"
    @page = Page.find_by_title(params[:id])
    
    puts @page.inspect
    
    
    if @page.nil?
      render :status => 404
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @page }
      end
    end
  end

  # GET /pages/new
  # GET /pages/new.xml
  def new
    @page = Page.new

    respond_to do |format|
      format.html {render :layout => 'admin'}
      format.xml  { render :xml => @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find_by_title(params[:id])
    render :layout => 'admin'
  end

  # POST /pages
  # POST /pages.xml
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to(@page, :notice => 'Page was successfully created.') }
        format.xml  { render :xml => @page, :status => :created, :location => @page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.xml
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to(@page, :notice => 'Page was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.xml
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to(pages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def get_title
    if @page.nil?
      return "Ruckus Demo"
    else
      return @page.title
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
<title>Ruckus administration center - start</title> 
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" /> 
<link href="/stylesheets/styleadmin.css" rel="stylesheet" type="text/css" media="screen" /><meta name="robots" content="noindex" /> 
</head> 
<body> 
 
<div id="menuheader"> 
	<div id="menu"> 
		<div class="menuitem"> 
			<span> 
				<img src="/images/menu/start.png" border="0" alt="" /> 
				<a href="/" title="start">View Site</a> 
			</span> 
		</div> 
		<div class="menuitem"> 
			<span> 
				<img src="/images/menu/pages.png" border="0" alt="" /> 
				<a href="/pages/" title="pages">pages</a> 
			</span> 
		</div>
		<!-- 
		<div class="menuitem"> 
			<span> 
				<img src="/images/menu/modules.png" border="0" alt="" /> 
				<a href="?action=modules" title="modules">modules</a> 
			</span> 
		</div>
		-->
		<!-- 
		<div class="menuitem"> 
			<span> 
				<img src="/images/menu/options.png" border="0" alt="" /> 
				<a href="?action=options" title="options">options</a> 
			</span> 
		</div>
		--> 
		<div class="menuitem"> 
			<span> 
				<img src="/images/menu/logout.png" border="0" alt="" /> 
				<a href="/users/sign_out" title="log out">log out</a> 
			</span> 
		</div> 
	</div> 
	<h1>Ruckus</h1> 
	<div id="statusbox"> 
		<!--
		<div> 
	<a href="?action=trashcan"><img src="/images/trash.png" alt="trashcan" title="trashcan" /></a> 
	0 items in trashcan</div> 
	-->
		<div> 
	<img src="/images/update-no.png" alt="" /> 
	ruckus is up-to-date</div> 
	</div> 
</div> 
 
<div id="text">
<%= yield %> 
<div id="somp">pluck &copy; 2005-2010 <a href="http://www.pluck-cms.org" target="_blank">pluck project</a>. pluck is available under the terms of the GNU General Public License.</div> 
</div> 
</body> 
</html>

app/views/layouts/install.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
<title>Ruckus - installation</title> 
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" /> 
<link href="stylesheets/styleadmin.css" rel="stylesheet" type="text/css" media="screen" /><script language="javascript" type="text/javascript" src="data/inc/tinymce/jscripts/tiny_mce/tiny_mce.js"></script> 
<script language="javascript" type="text/javascript"> 
<!--
//Enter-listener
if (document.layers)
	document.captureEvents(Event.KEYDOWN);
	document.onkeydown =
	function (evt) {
		var keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
		if (keyCode == 13)   //13 = the code for pressing ENTER
 
		{
			document.form.submit();
		}
	}
//-->
</script> 
</head> 
 
<body> 
<div id="menuheader"> 
<div id="menu2"> 
	<span class="menuitem2">installation</span> 
</div> 
<h1>Ruckus</h1> 
</div> 
 
<div id="text">		<span class="kop2">installation</span> 
	<%= yield %>
	<div id="somp">pluck &copy; 2005-2010 <a href="http://www.pluck-cms.org" target="_blank">pluck project</a>. pluck is available under the terms of the GNU General Public License.</div> 
</div> 
</body> 
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Ruckus Demo - Ruckus Demo</title> 
	<link href="/stylesheets/style.css" rel="stylesheet" type="text/css" media="screen" /> 
	<meta name="title" content="Ruckus Demo" /> 
  <%= csrf_meta_tag %>
</head>
	<body>
		<div id="container">
			<div id="hd"> 
				<h2><a href="/" style="color:#FFF;font-weight:normal;text-decoration:none !important;">Ruckus Demo</a></h2> 
				<ul>
				 	<% @pages.each do |p| %>
					<li><a href="/pages/<%= p.title %>" class="<% if @page.title == p.title %>act<% end %>"><%=p.title %></a></li>
					<% end %>
				</ul> 
			</div> 
			<div id="ct">
				<%= yield %>
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
			</div>
			<div id="ft">
				<a href="/pages/">admin</a></a>
			</div>
		</div>
	</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h2>Editing page</h2>

<%= render 'form' %>

<%= link_to 'Show', "/#{@page.title}", :target => "blank" %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h2>pages</h2><p><strong>Here you can manage, edit and delete your pages.</strong></p> 
	<div class="menudiv"> 
		<span> 
		<a href="/pages/new" ><img src="/images/newpage.png" alt="New Page" /></a> 
		</span> 
		<span> 
			<span> 
				<a href="/pages/new" >new page</a> 
			</span> 
						<br /> 
					</span> 
	</div>
	<!-- 
	<div class="menudiv"> 
		<span> 
			<a href="?action=images" ><img src="/images/image.png" alt="" /></a> 
		</span>
		<span> 
		<span> 
			<a href="?action=images" >manage images</a> 
		</span>
			<br /> 
		</span> 
	</div> 
	-->
			<% @pages.each do |p| %>
			<div class="menudiv"> 
				<span> 
					<img src="/images/page.png" alt="<%= p.title %>" /> 
				</span> 
				<span class="title-page"><%= p.title %></span> 
				<span> 
					<a href="/pages/<%=h p.title  %>/edit"><img src="/images/edit.png" title="edit page" alt="edit page" /></a> 
				</span> 
				<!--
				<span> 
					<a href="?editmeta=kop1.php"><img src="/images/siteinformation.png" title="edit page information" alt="edit page information" /></a> 
				</span> 
				-->
				<!--
				<span> 
					<a href="?pageup=kop1.php"><img src="/images/up.png" title="change page order" alt="change page order" /></a> 
				</span> 
				<span> 
					<a href="?pagedown=kop1.php"><img src="/images/down.png" title="change page order" alt="change page order" /></a> 
				</span> 
				-->
				<span> 
					<a href="/pages/<%=h p.title %>/destroy"><img src="/images/delete.png" title="move item to trashcan" alt="move item to trashcan" /></a> 
				</span> 
			</div>
			<% end %>

app/views/pages/new.html.erb
<h2>New page</h2>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1> 

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>


<% if user_signed_in? %>
<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>
<% end%>